### ISSUE TITLE
Updates to i18n documentation

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-upload#104]
There seems to be some inconsistency in the i18n documentation.

First there’s the listing of the default i18n object values, but in the following example, there are some different keys used, namely `addFile` and `addFiles` instead of `addFiles.one` and `addFiles.many`.

The documentation should also instruct to use `upload.set("i18n.addFiles.one`, "[translation]");` when changing just one key in the map instead of the whole map.

**Comment by stramel** [comment]
I think this stuff has been addressed. `addFiles` is a object now and there is a demo that uses `upload.set`

**Comment by jouni** [comment]
So it seems. Thanks!
