### ISSUE TITLE
Dropping a file on a nodrop element will disable the button.

### ISSUE THREAD

**Issue by juniperbelmont** [vaadin/vaadin-upload#107]
Recreate: try to drop an item on the nodrop element (https://cdn.vaadin.com/vaadin-elements/master/vaadin-upload/demo/)
Then try to click the button.

The drop should not be allowed, but the button should remain active for further use.

**Comment by stramel** [comment]
Not seeing this on Ubuntu 16.04 running Chrome 55. I'm wondering if this is specific to OS and browser. Will try on my Windows machine later.

**Comment by juniperbelmont** [comment]
I can replicate this on OSX El Capitan with Firefox, Chrome stable and canary, and Safari.
Not sure what I'm doing wrong.

Note: I don't show it in the gif, but I am able to tab to the button and access the dialog box by hitting space. It's just the mouse click that seems broken.

![repro](https://cloud.githubusercontent.com/assets/4591840/22384746/8ba0150e-e484-11e6-8d7c-904feb6481fa.gif)

**Comment by stramel** [comment]
@juniperbelmont Ah, yes, I am able to reproduce this bug. Thank you for the screen capture.
