### ISSUE TITLE
Cannot upload pdf files

### ISSUE THREAD

**Issue by samcarecho** [vaadin/vaadin-upload#110]
I've set the element "accept" attribute to 
```
accept="image/*,video/*,application/pdf"
```
But trying to upload PDF files always throws the "wrong file type" error.

Am I doing something wrong or is this this a bug?

Thanks

**Comment by platosha** [comment]
Hi! Looks like a bug that we have fixed last week.

Could you, please, try if the master branch works for you?

**Comment by samcarecho** [comment]
@platosha,

Indeed the code on the master branch works fine. I can now restrict upload of only PDF files.
Thanks

**Comment by jouni** [comment]
Thanks for the confirmation. I’ll close this issue then :)

**Comment by platosha** [comment]
@samcarecho FYI: vaadin-upload v1.0.1 with the fix was released today.
