### ISSUE TITLE
Vaadin-upload wrong file size while uploading.

### ISSUE THREAD

**Issue by samcarecho** [vaadin/vaadin-upload#115]
When uploading a file, vaadin upload progress bar shows the file size multiplied by 2.

for example, if uploading a 3Mb file, the progress bar will show the size of the files as 6Mb.
<br>
tested on: 
Chome Version 51.0.2704.103 m (64-bit)
vaddin-upload v1.0.1

**Comment by platosha** [comment]
Hello, I can not reproduce the issue. Have you changed any properties of the `vaadin-upload` element? Are you using the upload element in an Angular 2 project? Does it happens with files of any type? What OS are you using? Can you send an example file that triggers this issue?

**Comment by samcarecho** [comment]
@platosha 

![image](https://cloud.githubusercontent.com/assets/830211/17228385/20ec09c8-54e9-11e6-8172-cf71ddbfda38.png)

Here follows the original file I was uploading when I took the screenshot.
[SpaTouch Menu Panel 42256_A.pdf](https://github.com/vaadin/vaadin-upload/files/389294/SpaTouch.Menu.Panel.42256_A.pdf)


- I'm testing on Chrome 52 running over Windows 10, but the issue is also reproducible on FF and Edge.
- Any type of allowed files reproduces the error.


Here is how vaadin-upload attributes are set:
```
<vaadin-upload id="uploader"
           class="layout vertical"
           accept="image/*,video/*,application/pdf"
           max-files="5"
           max-file-size="[[maxFileSizeByte]]"
           target="/api/attachments"
           method="POST"
           headers="{'Accept': 'application/json', 'Content-Type': 'multipart/form-data'}"
           timeout="30000">
```

**Comment by Saulis** [comment]
Can't reproduce the issue still – could you help to debug by setting a breakpoint to https://github.com/vaadin/vaadin-upload/blob/master/vaadin-upload.html#L599 and making sure that `e.total` is correctly `3067170` bytes. Thanks!

**Comment by jouni** [comment]
I’m closing this issue as it has been inactive for so long. Please comment if you still have this issue.
