### ISSUE TITLE
RegExp for accept attribute is not case-insensitive

### ISSUE THREAD

**Issue by robrez** [vaadin/vaadin-upload#118]
If accept is set to file extensions, `jpg,pdf,txt`, the file selection dialog will allow files to be selected regardless of case, `JPG,PdF,Txt`. The `_addFile` routine will reject the files because the RegExp evaluates as false.

Is it OK to submit a PR using a case-ignore flag?
https://github.com/vaadin/vaadin-upload/blob/master/vaadin-upload.html#L729

eg:
```javascript
//replace this
var re = new RegExp('^(' + this.accept.replace(/[, ]+/g, '|').replace('/*', '/.*') + ')$');
//with this
var re = new RegExp('^(' + this.accept.replace(/[, ]+/g, '|').replace('/*', '/.*') + ')$', 'i');
```

**Comment by jouni** [comment]
Good catch, thanks. A PR would be great, of course 👍
