### ISSUE TITLE
Double clicking the upload button opens the file dialog twice

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-upload#122]
If you click the button twice before the dialog opens for the first one, a second dialog will appear right after the first one is closed

**Comment by samiheikki** [comment]
@tomivirkki what OS? Can't reproduce on Windows.

**Comment by stramel** [comment]
@tomivirkki Can you provide a way to reproduce? I can't trigger it on Ubuntu using Chrome

**Comment by tomivirkki** [comment]
Can't reproduce with the latest version anymore. Closing.
