### ISSUE TITLE
Local "upload"

### ISSUE THREAD

**Issue by NicolasRannou** [vaadin/vaadin-upload#127]
Is it possible to "upload" to the browser rather than a remote server?

I'd like to be able to parse all files in JS using the "FileReader" API but need a good way to:
* to properly prevent the vaadin-upload to push data to a remote server,
* display status complete for each file
* when to access the files property so I can work off it

Cheers

**Comment by NicolasRannou** [comment]
Currently doing the following - works OK but seems pretty hacky:
```
<vaadin-upload on-upload-request="_uploadRequest" files="{{files}}"></vaadin-upload>

  <script>
    Polymer({
      is: 'my-view1',
      _uploadRequest: function(event){
        // cancel AJAX Request
        event.preventDefault();

        // Update UI
        var files = this.files;
        if(files[0]){
          files[0].status = "";
          files[0].complete = true;
          files[0].progress = 100;
          files[0].uploading = false;
          
          // fire event
          var event = new CustomEvent('file-received', { 'detail': files[0] });
          this.dispatchEvent(event);
        }
      }
    });
  </script>
```

**Comment by platosha** [comment]
Yes, this is almost the way it is intended. I would also suggest the following changes:

- When the `upload-request` event is dispatched, the XHR is already opened and ready to be send. Preventing `upload-request` without sending or aborting the request manually will leave the request in the opened state forever, which is probably not good. Prevent the `upload-before` event instead.

- After preventing the `upload-before` event, the file UI state will remain clean. It would be easier to manipulate, for your case you will only have to set two properties: `complete = true` and `progress = 100`.

- Please use Polymer’s property accessor methods when setting file properties. This way your changes will propagate in the UI at any time.

```html
<vaadin-upload id="upload" on-upload-before="_uploadBefore"></vaadin-upload>
<script>
  Polymer({
    is: 'my-view1',
    _uploadBefore: function(event) {
      // Prevent AJAX request
      event.preventDefault();
      
      var file = event.detail.file;
      var fileIndex = this.$.upload.files.indexOf(file);
      
      // Update UI
      this.$.upload.set(['files', fileIndex, 'progress'], 100);
      this.$.upload.set(['files', fileIndex, 'complete'], true);
      
      // Fire event
      this.fire('file-received', file);
    }
  });
</script>
```

**Comment by NicolasRannou** [comment]
Thanks!
