### ISSUE TITLE
How to clear the uploads for vaadin upload? 

### ISSUE THREAD

**Issue by nikitasakhuja** [vaadin/vaadin-upload#128]
The previous uploads are not cleared when I am trying again to upload images the second time for a different component.
![vaadin](https://cloud.githubusercontent.com/assets/19816682/19546703/8d3b1f8a-96af-11e6-8fcb-8fe0a20d596e.png)

I want to clear these uploads when I re-route to this component.
Any help will be greatly appreciated!

**Comment by platosha** [comment]
Hi! This is simple as:

```javascript
    upload.files = [];
```

..., where `upload` is a `<vaadin-upload>` DOM element.

Please mind, if you’re using data binding for the `files` property, then you probably should clear the your bound files array instead.

**Comment by nikitasakhuja** [comment]
Hey ! Thanks a lot. It helped.
