### ISSUE TITLE
onreadystatechange fired only once

### ISSUE THREAD

**Issue by jay8t6** [vaadin/vaadin-upload#130]
upload-success and upload-error events never fire when I try to upload a picture using this component, progress seems to fire correctly. any idea whats causing this? I noticed that onreadystatechange is only firing once.

**Comment by samiheikki** [comment]
Hi @jay8t6 

Can you provide a demo or a code example where this issue can be re-produced? I tried it in our demo page and seems to work https://cdn.vaadin.com/vaadin-core-elements/master/vaadin-upload/demo/.

**Comment by platosha** [comment]
Closing because we were unable to reproduce this issue.

Feel free to reopen if still relevant. Please provide steps to reproduce and/or a code snippet.
