### ISSUE TITLE
 Unable to upload a xls file in chrome.

### ISSUE THREAD

**Issue by ravindrachougule** [vaadin/vaadin-upload#135]
To replicate Modified the below code from the demo sample.
Code snippet:
```
    <h3>Basic Usage...</h3>
    <demo-snippet>
      <template>
        <vaadin-upload accept="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.ms-excel,application/msexcel,application/pdf,image/*,application/vnd.*,application/msword"></vaadin-upload>
      </template>
    </demo-snippet>
```
Chrome version: Version 54.0.2840.98 (64-bit)
vaadin-upload version": "1.1.0

Note: This works fine on firefox and Safari.

**Comment by Saulis** [comment]
Hi!

What OS are you running. Both `.xls` and `.xlsx` worked for me with that snippet on Chrome 54&55 on OSX.

**Comment by ravindrachougule** [comment]
I am using OSX Yosmite 10.10.5

**Comment by Saulis** [comment]
Do you still have the problem?

**Comment by tomivirkki** [comment]
Worksforme. Reopen if still relevant.

**Comment by tepi** [comment]
Still broken for me. Latest Chrome Version 73.0.3683.103 (Official Build) (64-bit) on mac os. Flow version 13.0.1 in use, so vaadin-upload version is 4.2.1.

When trying to upload an XLS file, nothing happens. No errors in console, no requests to the server.

I have the following mime types allowed for the upload:
`"application/vnd.ms-excel"
"application/msexcel"
"application/x-msexcel"
"application/x-ms-excel"
"application/x-excel"
"application/x-dos_ms_excel"
"application/xls"
"application/x-xls"
"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"`

**Comment by tomivirkki** [comment]
![upload](https://user-images.githubusercontent.com/1222264/57453887-3570cf80-7270-11e9-927e-8c884759ba73.gif)

@tepi Seems to be working with the above MIME type list. Can you provide an example where the issue is reproducible?

**Comment by web-padawan** [comment]
Closing as inactive. Let's reopen again if we have a reproduction.
