### ISSUE TITLE
Property 'detail' does not exist on type 'Event'.

### ISSUE THREAD

**Issue by Chabane** [vaadin/vaadin-upload#138]
Hi,

I have this error : 
`Property 'detail' does not exist on type 'Event' `
in typescript project. How can I ignore this?

Thanks.

**Comment by platosha** [comment]
Explicit casting to `any` should help: `(<any>event).detail`.

The events with the detail key are `CustomEvent`s, so the cleaner way would be: `(<CustomEvent>event).detail`.

**Comment by Chabane** [comment]
thanks, that's work fine!

**Comment by raviashar** [comment]
When I am trying to using <any> keyword in mouse wheel scrolling. It's not working properly in firefox.
below is my code please help me.
mouse wheel is not working properly in firefox mozila.

angular.element('.newtoolbar-tools').bind('mousewheel onmousewheel DOMMouseScroll', (event) => {
            

            var a = window.event || event;
            var delta = Math.max(-1, Math.min(1, ((<any>a).wheelDelta || (<any>-a).detail)));

            if (delta > 0) {
                scope.ScrollUp();
            }
            else {
                scope.ScrollDown();
            }

            event.returnValue = false;

            // for Chrome and Firefox
            if (event.preventDefault) {
                event.preventDefault();
            }

        });

**Comment by ChandruD103** [comment]
> Explicit casting to `any` should help: `(<any>event).detail`.
> 
> The events with the detail key are `CustomEvent`s, so the cleaner way would be: `(<CustomEvent>event).detail`.

I have issue in using the category in the eventTarget interface "e.target.category"   exception as  "Property 'category' does not exist on type 'EventTarget' " and
issue in ClickEvent "e.point.x" exception as "Property 'point' does not exist on type 'Event'". Things work on serve--o but not able to build --prod
