### ISSUE TITLE
vaadin-upload should not use iron-icons

### ISSUE THREAD

**Issue by bennypowers** [vaadin/vaadin-upload#143]
the `vaadin-upload` polymer element imports `vaadin-upload-file` which in turn imports `iron-icons` this breaks apps where the `icons` id is taken by a custom icon set.

Likewise, `vaadin-upload-icons` should implement its own set of icons, rather than importing the entire `iron-icons` set. 

This will also drastically reduce file sizes.

**Comment by bennypowers** [comment]
I've worked around this by changing my bower.json entry from 
    "vaadin-upload": "vaadin/vaadin-upload#^1.1.0"
to
    "vaadin-upload": "vaadin/vaadin-upload#master"

**Comment by Saulis** [comment]
Hi!

Looks like we've fixed this in #132 but haven't actually released it (duh). Gonna release a maintenance version asap.

**Comment by Saulis** [comment]
There we go, released `v1.1.1` – sorry about the trouble!

**Comment by bennypowers** [comment]
Confirming, my app works as expected now. Thank you for the extremely quick response! Ten points! 🍻
