### ISSUE TITLE
File upload button not working on iOS

### ISSUE THREAD

**Issue by jdoltar** [vaadin/vaadin-upload#145]
Nothing happens when tapping the file upload button. It appears this is due to Safari not allowing click events on file input buttons that have `display: none`.

I was able to workaround this by removing the `hidden` attribute on the file input button and applying the following styles to it:
```
      input[type="file"] {
        display: block;
        width: 111px;
        height: 36px;
        opacity: 0;
        overflow: hidden;
        margin-top: -36px;
        cursor: pointer;
      }
```

**Comment by platosha** [comment]
Thanks for reporting. I’ve looked into this, seems to be an issue in Polymer, introduced in v1.7.1. Works for me with polymer v1.7.0 and below.

Could you also try downgrading Polymer as a workaround?

**Comment by platosha** [comment]
See polymer/polymer#4242
