### ISSUE TITLE
add notify to i18n

### ISSUE THREAD

**Issue by jay8t6** [vaadin/vaadin-upload#152]
Is there a reason why i18n doesn't notify? This can be useful if I only want to update part of the object, like if I only want to update the error message.

**Comment by platosha** [comment]
Hi,

You can use the `set` method to make a partial (subproperty) change and notify the component about the change at the same time:

```javascript
upload.set('i18n.error.tooManyFiles', 'Too many files');
```

Setting `notify: true` flag will allow the changes to propagate back from inside the component with two-way bindings. But it does not notify the component of the changes made from outside, so I don’t think this is helpful for your use case.
