### ISSUE TITLE
Polymer 2.0 Support

### ISSUE THREAD

**Issue by Saulis** [vaadin/vaadin-upload#156]
- Use latest `v2.0.0-rcX`
- Aim for Hybrid if feasible
- Add "variants" for "2.x" dependencies in `bower.json`
- Plan is to release this as `2.0` and then deprecate the Polymer v1 support.
  - There is going to be a breaking API change because of we need start using named slots instead of class selectors for child elements.

- Follow steps from https://www.polymer-project.org/2.0/docs/upgrade for more details.

**Comment by juniperbelmont** [comment]
I am planning on doing this to write a blog post / case study. It's probably the lightest weight component we have and should help me figure out Polymer 2.0 so I can talk about it.

Yes yes?

**Comment by Saulis** [comment]
@juniperbelmont sounds good! Keep us posted and don't hesitate to ask if/when you bump into some issues.
