### ISSUE TITLE
Long filenames make the "abort" button disappear on Firefox

### ISSUE THREAD

**Issue by artemperl** [vaadin/vaadin-upload#157]
When the filename is wider than the vaadin-upload element, the abort button isn't displayed anymore in the file list.

Used Firefox 52 on macOS Sierra 10.12.3
Works fine in Chrome and Safari

**Comment by tomivirkki** [comment]
Thanks for reporting, fix in https://github.com/vaadin/vaadin-upload/pull/162

**Comment by tomivirkki** [comment]
Released in https://github.com/vaadin/vaadin-upload/releases/tag/v1.1.4
