### ISSUE TITLE
handle max-file-size rejection internally

### ISSUE THREAD

**Issue by davidmaxwaterman** [vaadin/vaadin-upload#177]
It seems like there would be some nice way for this element to handle the rejection of each file due to max-file-size internally on its UI, in a similar way to when there's a server error where you get a nice big red message for each file that has an error. Any chance?

**Comment by manolo** [comment]
You mean to add the file to the queue with the error flag and error message set ?
That is not considered right now, but you could use this workaround.

Use [max-file-size](https://cdn.vaadin.com/vaadin-core-elements/master/vaadin-upload/#vaadin-upload:property-maxFileSize) property to limit the size in bytes, and listen to the [file-reject](https://cdn.vaadin.com/vaadin-core-elements/master/vaadin-upload/#vaadin-upload:event-file-reject) event. When the event happens, add the file with the error set to the uploader queue.

```
      upload.maxFileSize = 300;
      upload.addEventListener('file-reject', function(e) {
        var file = e.detail.file;
        file.error = e.detail.error;
        upload.push('files', e.detail.file);
      })

```

**Comment by davidmaxwaterman** [comment]
> You mean to add the file to the queue with the error flag and error message set ?

Yes, I think so.

You're work-around sounds fine. I'll give it a shot, thanks.

I must admit, I find the system of events and preventDefault() to be really quite flexible. I only wish that more common use-cases were illustrated in the examples/demos. As it is, I find I need to figure out ways to do what I had thought the widget would do on its own. Anyway, I'm quite liking the design, even though I needed to fork it to switch from a form to a filereader.

**Comment by web-padawan** [comment]
Closing per above comment, as this is proven to be doable with event listener.
