### ISSUE TITLE
Depend on Polymer 2 by default

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-upload#178]
Make P2 the mainline and P1 the variant (with 2.0-preview dependencies). This should be fixed for the 2.0.0 alpha.

**Comment by stramel** [comment]
... :/ Brought this up in the 2.0-preview PR. Don't remember why you guys decided not to do this.

**Comment by Saulis** [comment]
Fixed in #180 

@stramel we wanted to avoid making breaking changes by switching the deps – however, we now realized that it's pretty hard to install the P2 compatible dependencies unless they're in the mainline.
