### ISSUE TITLE
"no-auto" property not working

### ISSUE THREAD

**Issue by doughaase** [vaadin/vaadin-upload#179]
The documentation states that I should use this property (no-auto) like this:

`<vaadin-upload id="manualUpload" no-auto></vaadin-upload>`

My code looks like this:

`            <vaadin-upload id="uploadComponent" max-files="30" accept="image/*" max-file-size="10000000"
                           target$="http://localhost/test/[[routeData.vehicleid]]"
                           headers$="[[storedUser.tokenHeader]]"
                           files="{{imageFiles}}"
                           nodrop 
                           no-auto>
            </vaadin-upload> `

... and it's still auto uploading the files.

**Comment by jouni** [comment]
This feature hasn’t been released yet in a stable version. You can use v2.0.0-alpha1 or the master branch to use this feature.

**Comment by doughaase** [comment]
Thanks, I'll try with the master branch.
