### ISSUE TITLE
retryAll()?

### ISSUE THREAD

**Issue by davidmaxwaterman** [vaadin/vaadin-upload#185]
I'd like to add a button that the user can click to retry all the failed uploads, instead of going down the list and clicking each individual restart icon. Please consider adding a retryAll() method that I can trigger from a button click handler.

**Comment by manolo** [comment]
You have the method [uploadFiles](https://cdn.vaadin.com/vaadin-core-elements/master/vaadin-upload/#vaadin-upload:method-uploadFiles) that does what you are asking for. It was introduced in [v2.0.0-alpha1](https://github.com/vaadin/vaadin-upload/releases/tag/v2.0.0-alpha1) release

**Comment by davidmaxwaterman** [comment]
Yeah, I guess so.

I suppose I was coming from this with the expectation that vaadin-upload would be a 'do it all' widget, without me having to add loads of functionality around it for things like this.

**Comment by manolo** [comment]
Yes that is, just call the `uploadFiles()` without any parameters and it does everything.

**Comment by davidmaxwaterman** [comment]
No, I mean it has the *UI* to 'do it all'...ie with a button that does that, and like the other buttons in the vaadin-upload element.
