### ISSUE TITLE
method ignored on Edge

### ISSUE THREAD

**Issue by davidmaxwaterman** [vaadin/vaadin-upload#187]
For some reason, vaadin-upload seems to try a POST on Edge, even though I've set method to PUT. It works fine on FF and Chrome, so it's a bit of a surprise. I've not investigated it yet. I'll post if I find anything more (but Edge is a pita to debug on).

**Comment by manolo** [comment]
I'm unable to reproduce the issue. I double tested with Edge 15.15063 and Edge 14.14393, and it sends correctly the method as configured.

My code is:

```
     <vaadin-upload id="upload" method="put">
     </vaadin-upload>
```

And [here](http://g.recordit.co/VPK6YXTsC8.gif) you have the video showing the request sent to the server. There is not server side in my case hence I get a 404 Not-Found error which is correct

**Comment by davidmaxwaterman** [comment]
Yes, your video shows how I would expect it to be. I'll see if I can find anything more.

**Comment by davidmaxwaterman** [comment]
OK, it was my mistake (it was some other xhr I was looking at). Apologies for the noise.

**Comment by manolo** [comment]
no problem.
