### ISSUE TITLE
advice for using dialog for managing a single multi-part upload?

### ISSUE THREAD

**Issue by davidmaxwaterman** [vaadin/vaadin-upload#193]
I would like to use this dialog to upload a large file using S3's multi-part upload API. Is it possible for someone to outline how this might be done?

<http://docs.aws.amazon.com/AmazonS3/latest/dev/uploadobjusingmpu.html>

I have been wondering if the progress bar might be split into several parts, with each part displaying the progress uploading that part (if concurrency is sufficient).

Perhaps a single large file being uploaded in parts could be represented as separate files in the dialog, each with its own progress/etc, and the calling code can do the work of splitting the file into parts and starting/ending the multipart uploads.

The latter seems to fit in best with the current design.

Any thoughts?

**Comment by platosha** [comment]
@davidmaxwaterman looks like this means there will be several requests per file. This does not fit into the built-in XHR workflow very well, unfortunately.

I would suggest to disable the internal XHR and implement the uploading externally. Start with this example, here is how to disable the XHR and update the progress and the complete state for the file manually: https://github.com/vaadin/vaadin-upload/issues/127#issuecomment-254788915

As per displaying progress per each part, this is not possible with the `<paper-progress>` we use internally. If you really need to display progress per part, you will need to implement a custom file list, see the example in `demo/advanced.html`. If you are happy with a single progress number for the entire file, you can update the progress manually in the built-in file display.

**Comment by platosha** [comment]
Closing as this is a question rather then an issue in the element.
