### ISSUE TITLE
_isSelected check doesn't work with paginated displays

### ISSUE THREAD

**Issue by stramel** [vaadin/vaadin-upload#200]
The `_isSelected` function uses `this.selectedItems.indexOf(item) > -1` which will always be false when the items replaced during page change. This is because new objects are created and this check is checking by reference.

 It would be good to do an actual object comparison here or provide a way to check a certain property for comparison.

**Comment by tomivirkki** [comment]
This was probably meant for the `<vaadin-grid>` repo.

We've been discussing adding a property (for item path) to specify which value should be used for comparing grid items. There's no GH issue for it however so I suggest moving this one to the Grid repo 👍

**Comment by stramel** [comment]
Shoot, yeah, was meant for `vaadin-grid`. Sorry, I will move it over there.
