### ISSUE TITLE
dropLabel should wrap on narrow viewports

### ISSUE THREAD

**Issue by marcushellberg** [vaadin/vaadin-upload#210]
When `<vaadin-upload>` is narrow, dropLabel should probably wrap and get shown under the button. Right now it gets cut off.

<img width="179" alt="screen shot 2017-09-02 at 10 03 02 am" src="https://user-images.githubusercontent.com/883698/29997365-f18b2b78-8fc5-11e7-8601-4c9562fea07b.png">

**Comment by manolo** [comment]
@platosha could we wrap this in vaadin-form-layout? or it sounds like a overwhelming solution.

**Comment by stramel** [comment]
Fairly certain this could just be as easy as `@apply --layout-wrap;` in `#buttonsPrimary`.

![image](https://user-images.githubusercontent.com/855184/30152689-925b6b60-9379-11e7-9692-8fda38a5cbb6.png)
