### ISSUE TITLE
Html-api documentation is empty on updated elements site

### ISSUE THREAD

**Issue by krumware** [vaadin/vaadin-upload#217]
The HTML-API documentation is empty on the new site.
Btw, looks awesome @marcushellberg!

https://vaadin.com/elements/vaadin-upload/html-api

**Comment by marcushellberg** [comment]
Looks like the filtering I'm applying to the analyzer is filtering out all of this. Probably a Hybrid-related issue. Thanks for reporting!

**Comment by web-padawan** [comment]
The link above now displays the documentation correctly, so I'm closing this issue.
