### ISSUE TITLE
Styling Shadow Dom parts

### ISSUE THREAD

**Issue by johnlim** [vaadin/vaadin-upload#222]
Hi, 
I'm a bit confused with the wording `The following shadow DOM parts are available for styling:`. My first impression was that they were custom css mixins. For `vaadin-upload`, am I right to assume that what it means is that I can customise it via slots? But for vaadin-upload-file, how can i style `row` as shown in  
https://github.com/vaadin/vaadin-upload/blob/4f9b08a553118f10ee82739791a05466e3d5537d/vaadin-upload-file.html#L125 ?
Thanks,
John

**Comment by jouni** [comment]
Hi! You should find all the documentation you need from here: https://github.com/vaadin/vaadin-themable-mixin/wiki

**Comment by jouni** [comment]
In short, no, they are not CSS mixins. They are just the named parts of the internal DOM that we promise will not remove/change within a major version of the element.
