### ISSUE TITLE
"vaadin-themable-mixin": "^1.1.0" requires Polymer 2 which leads to ECONFLICT Unable to find suitable version for polymer

### ISSUE THREAD

**Issue by wenzel-k** [vaadin/vaadin-upload#229]
https://github.com/vaadin/vaadin-upload/blob/4bb3955f3dd364441cf8004b67d62dfd86173faa/bower.json#L39

When you try to 'bower install --save vaadin/vaadin-upload#^2.1.2' or bower install --save vaadin/vaadin-upload on an Polymer 1 project it will result in an error.

My tmp workaround is via .bowerrc and
`"ignoredDependencies": [
		"vaadin-themable-mixin"
	]`

Best regards
Wenzel

**Comment by manolo** [comment]
@wenzel-k can you test if fix in 2.x branch fixes the problem? you need to depend on '#2.x' in your bower

**Comment by wenzel-k** [comment]
@manolo it works now 👍

Thank you!
