### ISSUE TITLE
Feature backlog

### ISSUE THREAD

**Issue by platosha** [vaadin/vaadin-upload#23]
### 1.x
- Pre-drop validation for file type/size/count
- Keyboard navigation
  - Open file dialog
  - Cancel/retry upload
  - Start upload
- ~~Manual upload start (#123)~~
- Queuing files
- Pause/resume queue
- Auto-retry on Error
- Custom content bound to remaining time, upload speed
- Receiving `fileId` and other file data from server
- Auto-clear list after complete
- File template
- File preview #63 
  - Fullscreen preview from thumbnail
- Fullscreen preview on click
- Prevent page reload while uploading
- Form support with file names and server data values
- Overall progress
- Long list support
- Custom (+ full viewport) drop zone support
- Floating status area
- `localStorage` support

**Comment by tomtom215** [comment]
Please sir, can we have these features? :)

- **File preview** (Most important for client-side validation of correct file before uploading files to server)
- **Fullscreen preview on click** (Because it would be pretty)

**Comment by jouni** [comment]
Thanks for the suggestions! File preview was already on the list, but fullscreen preview is a nice enhancement for it.

No timeline for these yet, but contributions are welcome!

**Comment by stramel** [comment]
Can we strikeout the items that have been completed and link the PR that added it or remove them from here?

**Comment by jouni** [comment]
@stramel absolutely. Would be great if you can dig up any relevant PRs, I can update the issue. I’ll split out any missing features into separate issues and close this one after that. Feels better IMO to have separate issues vs this mega-issue.

**Comment by tomivirkki** [comment]
Closing, prefer feature requests as separate issues (easier to manage & discuss)
