### ISSUE TITLE
Add capture option

### ISSUE THREAD

**Issue by BorntraegerMarc** [vaadin/vaadin-upload#231]
To trigger immediately the camera from vaadin upload I would like to specify `<vaadin-upload capture="environment">`

**Comment by BorntraegerMarc** [comment]
Would you be open for a PR?

**Comment by stramel** [comment]
@BorntraegerMarc I have covered this in the refactored version but I might be able to slide this into the current version pretty easily as well.

#201 and #227 are what I'm referring to with the refactored version.

**Comment by BorntraegerMarc** [comment]
@stramel nice 😄 Do you have an ETA when it's released?

**Comment by tomivirkki** [comment]
This is available in the latest version. Closing.
