### ISSUE TITLE
Remove the paper-ripple hack

### ISSUE THREAD

**Issue by platosha** [vaadin/vaadin-upload#24]
There’s a monkey patch in vaadin-upload for paper-ripple internal radius calculation. The purpose of the monkey path is
- to remove the Ripple.MAX_RADIUS limit (which is not customisable),
- to have a little nicer animation formula for large container ripples that we have.

We need to remove this hack when paper-ripple would expose the `maxRadius` property.

See:
- issue for exposing Ripple.MAX_RADIUS in the `paper-ripple` repo: https://github.com/PolymerElements/paper-ripple/issues/27
- `paper-ripple` rewrite PR: https://github.com/PolymerElements/paper-ripple/pull/63
  And

**Comment by tomivirkki** [comment]
The latest version no longer uses MD/Paper. Closing.
