### ISSUE TITLE
components dont load in browser on initial install

### ISSUE THREAD

**Issue by musicsmithnz** [vaadin/vaadin-upload#253]
Anyone else having trouble with version changes or something? I followed the instructions completely and the components did not load in the browser. Firstly, the index.html file references the parent directory, outside the github repository with "..". should it be assumed dependencies are installed outside the repository?
In fact the webcomponentsjs is not even installed under npm. The Installation does not mention needing outside repositories. I'm curious how this is working for others?

**Comment by platosha** [comment]
Please make sure that you have `/components/vaadin-upload/` in your address bar.

`$ polymer serve` is supposed to serve the component root from that address. Having that, `..` relative path resolves to `/components/` , where all the dependencies are served from `bower_components/` inside the repository.

**Comment by platosha** [comment]
You should also be able to see live demos of the component at `/components/vaadin-upload/demo/`.

**Comment by tomivirkki** [comment]
Closing as inactive
