### ISSUE TITLE
Trigger opening filepicker with method call

### ISSUE THREAD

**Issue by yglodt** [vaadin/vaadin-upload#254]
I would like to trigger opening the filepicker with a method call on the <vaadin-upload>, e.g. by clicking on a profile picture.

I am currently using version 2.1.3 because I am on Polymer 1.x for now.

**Comment by peterblazejewicz** [comment]
Would it work? Within your click handler (required user action):
```
upload.$.fileInput.trigger('click')
```
'upload' is reference to the component. How to trigger 'click' (via library or with MouseEvent) depends on your choice. The point is to execute this as results of click handler.

**Comment by yglodt** [comment]
Almost. This worked:

	var clickEvent = new MouseEvent("click", {
		"view": window,
		"bubbles": true,
		"cancelable": false
	});

	this.$.uploader.$.addButton.dispatchEvent(clickEvent);
