### ISSUE TITLE
No event sent to back-end when files change.

### ISSUE THREAD

**Issue by TomiZet** [vaadin/vaadin-upload#270]
vaadin-upload component has 'files' property which is an array of file objects. At back-end it is possible to register propertyChangeListener for this property via method addFilesChangeListener. However component sends this event only when this property is initialized. In the runtime no event is sent neither in case new file is added nor in case uploaded file is removed. For more details see also vaadin/components gitter, message from 07th June 2018, Question#2

**Comment by limonte** [comment]
Both in this repository and in the vaadin/components gitter we're providing the front-end support. Please limit your question/issue-report to front-end only.

**Comment by limonte** [comment]
Closing this issue for the same reason as in https://github.com/vaadin/vaadin-upload/issues/269#issuecomment-396879647
