### ISSUE TITLE
File select dialog doesn't display on mobile

### ISSUE THREAD

**Issue by admwx7** [vaadin/vaadin-upload#281]
### Description
A recent update started causing programmatic clicks on mobile and touch devices to stop working when Polymer is included in your web app, this is the core of upload in the browser and thus this element is now broken as well. I've implemented a workaround in my app, but as this has been an issue with 1.x and 2.x polymer for 2 months now and hasn't got a response from the team it's unlikely to be fixed. The issue and workaround are posted here: https://github.com/Polymer/polymer/issues/5289

### Expected outcome
Clicking the upload file button on mobile should give the file selection dialog

### Actual outcome
Nothing happens

### Live Demo
Oddly enough I couldn't recreate in jsfiddle. Was able to replicate without issues in a fresh index.html by just including the polymer library and nothing else.

### Steps to reproduce
1. Put a `vaadin-upload` element in the page.
2. Use the console in chrome to change to mobile view
3. Click the "Upload Files..." button.

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [x] Android Chrome

**Comment by web-padawan** [comment]
Hi, have you tried the latest patch release published today? Check demos here: https://cdn.vaadin.com/vaadin-upload/4.0.1/demo/#upload-basic-demos

**Comment by admwx7** [comment]
Tracked down the issue yesterday, looks like you've got a fix in already, closing this issue then.
