### ISSUE TITLE
Remove file uploaded by a user

### ISSUE THREAD

**Issue by KrifaYounes** [vaadin/vaadin-upload#284]
It's possible to remove file uploaded from a list ? 
When I upload a file, I insert a object into a list like this : 

     
```
List<fileUploadDtoList> fileUploadDtoList =  new ArrayList();
uploadFileButton.addSucceededListener(event -> {
            InputStream inputStream = buffer.getInputStream(event.getFileName());

            if(inputStream != null) {
                FileUploadDto fileUploadDto = new FileUploadDto();
                fileUploadDto.setFileName(event.getFileName());
                fileUploadDto.setMimeType(event.getMIMEType());
                byte[] bytes = IOUtils.toByteArray(inputStream);
                fileUploadDto.setByteArrayDocument(bytes);
                fileUploadDtoList.add(fileUploadDto);
            }
        });
```

I want to remove the file from fileUploadDtoList  when the user remove the file.
It's possible to do somethink like that : 

```
uploadFileButton.addRemoveFileListener(event -> {
    event.getFileName(); removeToFileUploadList();...
}
```

**Comment by TatuLund** [comment]
See discussion here: https://vaadin.com/forum/thread/17336034/remove-file-uploaded-vaadin-upload

**Comment by iatomic** [comment]
We must fix the Upload component as even though we got it to work it is throwing exceptions 
on the client side to the point that it scares users so bad that we may have to entirely remove it from use as totally unfit for production. Any idea how to choke JS exceptions it is throwing (how to get them choked those exception popups are trully ANNOYING)? see images below. upload works but it keeps still throwing exceptions ruin any decent/acceptable  user experience. see below images.

![terror](https://user-images.githubusercontent.com/42481030/47971510-9a195a80-e092-11e8-94fb-5b69f5b4369b.png)
![upload-error](https://user-images.githubusercontent.com/42481030/47971512-9c7bb480-e092-11e8-98d3-5bc84a06600a.png)

**Comment by iatomic** [comment]
did you try tinkering with
```
 upload.getElement().addEventListener("file-remove", new DomEventListener() {
		@Override
		public void handleEvent(DomEvent arg0) {
			component.setVisible(false);
		}
	});
```

?

upoad truly needs a LOT of work. especially the JS excpetons being thrown disqualify it from being ready for anything but a testing for fun solution

**Comment by iatomic** [comment]
is anyone looking at this upload-flow component.... it is truly a major pain for any production project.

**Comment by web-padawan** [comment]
Closing in favor of vaadin/vaadin-upload-flow#63, please continue discussion there. It would be easier for the team to have it in 1 place, and this repository is for Web Component, not Java counterpart.
