### ISSUE TITLE
vaadin upload to fire an event when a file is removed from it

### ISSUE THREAD

**Issue by Klaudeta** [vaadin/vaadin-upload#285]
It would be helpful to have an event fired from the vaadin-upload web component when a file is removed from the list, same way as the other events (upload-success, upload-error, upload-start, etc) are fired.

**Comment by samiheikki** [comment]
I believe you can use `vaadin-upload-file`'s `file-remove` event which also bubbles to `vaadin-upload`. https://github.com/vaadin/vaadin-upload/blob/master/src/vaadin-upload-file.html#L123

**Comment by klaussemarsse** [comment]
That event has been stopped to further propagate from _onFileRemove method.
https://github.com/vaadin/vaadin-upload/blob/master/src/vaadin-upload.html#L783
So options I could think about would be to either remove the stopPropagation call or have vaadin-upload dispatch its own file-removed event.

**Comment by Klaudeta** [comment]
That event has been stopped to further propagate from _onFileRemove method.
https://github.com/vaadin/vaadin-upload/blob/master/src/vaadin-upload.html#L783
So options I could think about would be to either remove the stopPropagation call or have vaadin-upload dispatch its own file-removed event.

**Comment by iatomic** [comment]
if (component != null) {
	vlowerLayout.remove(component);

}
component = createComponent(event.getMIMEType(), event.getFileName(), buffer.getInputStream());
if (component instanceof Image) {
	upload.getElement().addEventListener("file-remove", new DomEventListener() {
		@Override
		public void handleEvent(DomEvent arg0) {
			component.setVisible(false);
		}
	});
	// upload.getElement().addEventData("event.detail.file.name");
}
p = new HtmlComponent(Tag.H3);
p.getElement().setText(event.getFileName());
vlowerLayout.add(component);

**Comment by heruan** [comment]
@iatomic what is that code? Could you elaborate on that, and you use proper formatting when pasting code? Otherwise, it's difficult for other to understand. Also, it seems Java code, but this is not the Java component repo.

**Comment by iatomic** [comment]
this is how the java component was used to go around issues related to lack of an event allowing for the removal of a file after it has been add/uploaded. listener is attached to file-remove.

**Comment by web-padawan** [comment]
This has been requested many times. Should be a new feature but can be also considered as a bug fix.

**Comment by samiheikki** [comment]
`file-remove` does seems to work in all browsers. Demo: https://jsfiddle.net/samiheikki/ex95g2j6/

@web-padawan so is the issue that it is not documented?

**Comment by web-padawan** [comment]
@samiheikki I think there is a misunderstanding about this line currently:

https://github.com/vaadin/vaadin-upload/blob/40ce6520737253c579b3d0d26504ac4f52dbdae9/src/vaadin-upload.html#L786

The `event.stopPropagation()` is expected to prevent the bubbling.
If that doesn't work, something is likely wrong. We should verify whether this line is needed.

Also, the `file-remove` event should be documented, if we are exposing it.

**Comment by web-padawan** [comment]
Change introduces in #50, let's check the conversation there first.

**Comment by samiheikki** [comment]
Well `file-remove` is documented in here: https://github.com/vaadin/vaadin-upload/blob/master/src/vaadin-upload-file.html#L191
And that event (along with other `file` events) have `bubbles: true`: https://github.com/vaadin/vaadin-upload/blob/master/src/vaadin-upload-file.html#L140

So I'd see that let's only remove this line: https://github.com/vaadin/vaadin-upload/blob/master/src/vaadin-upload.html#L786. And no need to add the same documentation to `vaadin-upload.html`.

@web-padawan do you agree?

**Comment by web-padawan** [comment]
@samiheikki sounds good to me.
