### ISSUE TITLE
Remove the droppable indication when dropping is disabled

### ISSUE THREAD

**Issue by platosha** [vaadin/vaadin-upload#29]
On some cases (e. g., for mobile), the developer might disable the drop files support by setting `nodrop` attribute/property. This makes the element to not handle the drop, removes the drop zone border, padding and label.

Though, the element still indicates the drop support if someone try to drag files over it with the ripple and cursor reaction. We should probably remove that indication as well.

**Comment by jounik** [comment]
We could expand the scope of this task to include validation feedback during drag-over also.

**Comment by samiheikki** [comment]
@jounik Can you elaborate what you meant by validation feedback?

**Comment by jounik** [comment]
@samiheikki the same thing @platosha has written as the second paragraph in the description (ripple and cursor). So remove the ripple effect and change the cursor to "no-drop". Can’t remember anything else right now.
