### ISSUE TITLE
There is not a 'clearSucceededListener'

### ISSUE THREAD

**Issue by ugurdoksan** [vaadin/vaadin-upload#302]
I think there must be a clearSucceededListener to realise the user clicked the clear button of any uploaded file...

**Comment by web-padawan** [comment]
The web component fires a `file-remove` event, which has been fixed by #299
Once we release a new version, you should be able to listen to it.

**Comment by web-padawan** [comment]
Closing as `4.2.2` was released, so you now can listen for `file-remove` event.

**Comment by ugurdoksan** [comment]
I can not see the corresponding method in Vaadin 14.0.3-beta version.

![Untitled](https://user-images.githubusercontent.com/24225109/59496678-a2443e80-8e9a-11e9-9d25-a649cba821c2.png)

**Comment by web-padawan** [comment]
@ugurdoksan sorry, I was a bit wrong in my explanation.

Here you can find a workaround which was previously blocked by absence of `file-remove` event:
https://vaadin.com/forum/thread/17336034/17362247

Let's discuss the request for Flow counterpart here: https://github.com/vaadin/vaadin-upload-flow/issues/63
