### ISSUE TITLE
A11y-Issue: File Upload after error

### ISSUE THREAD

**Issue by MarcusMorba** [vaadin/vaadin-upload#308]
I installed the "Base Starter" (https://vaadin.com/start/latest/polymer) and the demo app has the following issue:

The File Upload had two "buttons" after showing an error which are not accessible as they are not buttons, but divs.

![image](https://user-images.githubusercontent.com/22810698/59272940-64a3a380-8c57-11e9-9308-6f35bdc2cd6b.png)

**Comment by web-padawan** [comment]
Appears to be the same as #311 so let me close this one as a duplicate.
