### ISSUE TITLE
intetic onchange event

### ISSUE THREAD

**Issue by juanda2222** [vaadin/vaadin-upload#320]
### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

**Comment by tomivirkki** [comment]
What is this issue about? Please provide a description etc

**Comment by juanda2222** [comment]
Mistakenly opened this issue. Just found out, sorry
