### ISSUE TITLE
FileBuffer getInputStream() is closed

### ISSUE THREAD

**Issue by Kai-W** [vaadin/vaadin-upload#334]
The Inputsream returned by the FileBuffer cant be accessed because it's closed.
```java
        FileBuffer buffer = new FileBuffer();
        Upload upload = new Upload(buffer);
        upload.addSucceededListener(event -> {
            System.out.println(buffer.getFileDescriptor().valid()); //false 
            try {
                buffer.getInputStream().read(); // java.io.IOException: Stream Closed
            } catch (IOException e) {
                e.printStackTrace();
            }
        });
```
The FileDescriptor is part of the Outputstream. 
Javadoc of FileDescriptor:
`Instances of the file descriptor class serve as an opaque handle to the underlying machine-specific structure representing an open file, an open socket, or another source or sink of bytes.`
So the Descriptor gets invalidated by closing the Outputstream.
`return new FileInputStream(  ((FileOutputStream) file.getOutputBuffer()).getFD());`
Creates a new Inputstream of a closed Fiel Descriptor.

**Comment by cheppsn** [comment]
Please fix, this is still not resolved with Vaadin 14.4.0...
