### ISSUE TITLE
Vaadin Upload premature AllFinishedEvent

### ISSUE THREAD

**Issue by lmorocz** [vaadin/vaadin-upload#368]
### Description
Vaadin's Upload component is sometimes sending AllFinishedEvent premature (before all SucceededEventListeners are finished). See: https://github.com/lmorocz/vaadin14.upload.premature.allfinished-demo/blob/main/README.md#notes

### Demo project
https://github.com/lmorocz/vaadin14.upload.premature.allfinished-demo

### Steps to reproduce
1. Build and run the demo project with maven, or your favourite IDE as usual. Load up http://localhost:8080/ in a browser.
2. Hit the "Generate Files" button to generate some test data with random byte content (20x2.77 MB files in a temp directory)
3. Upload the generated files (all 20 of them at once) and watch the LOG TextArea
4. Check the LOG TextArea, if the "AllFinishedEvent occurred!" message is not at the bottom then you got the AllFinishedEvent premature. If not, then hit "Clear LOG" button, and repeat form 3.

### Expected outcome
AllFinishedEventListener only runs after all SucceededEventListener (or other failure/rejected EventListeners) are finished.

### Actual outcome
AllFinishedEventListener sometimes runs before all SucceededEventListener (with lengthy processing logic) are finished.

### Using
* Vaadin v14.4.3 and also v18.0.0.beta3
* Spring-Boot v2.3.6-RELEASE
* Tomcat 9.0.39 (from Boot's BOM)
* Chrome v87.0.4280.66 (64-bit)
* Firefox v83.0 (64-bit)

**Comment by szembek** [comment]
This is definitely an issue we are still encountering

**Comment by rolfsmeds** [comment]
More details from another user:

> To produce the bug, I built the application as a WAR and deployed it to Tomcat on a remote server. 
> 
> Then, I connected to a Japanese ProtonVPN server (~300 ms ping, ~1 mb/s upload speed) and opened the application.
> 
> I then uploaded a batch of 4 .CSV files at once (test1-test4), waited for the progress bars to show the uploads were completed, then uploaded another batch of 4 files (testa-testd).  The file sizes ranged from ~1kb to ~150kb.
> 
> Then I viewed the output on our server’s Tomcat Catalina log.
> 
> You can see in the attached screenshot that UploadSuceededEvents fired after a batch’s UploadAllFinishedEvent, and a file from the first batch is present in the buffer during the second batch’s UploadAllFinishedEvent.
> 
![vaadin-upload-test](https://user-images.githubusercontent.com/4611559/112804265-e22ee280-907c-11eb-8068-fbd40aa8aaaa.png)

Example project:
[upload-test.zip](https://github.com/vaadin/vaadin-upload/files/6220119/upload-test.zip)

**Comment by lmorocz** [comment]
Thanks for the fix @sissbruecker ! 

Would you be so kind as to backport it to the old `vaadin-upload` repo for the Vaadin 14.x LTS line?

**Comment by sissbruecker** [comment]
@lmorocz I can ask internally if we want to do it. Not guarantees that it will happen though.

**Comment by web-padawan** [comment]
This is actually already backported, see https://github.com/vaadin/vaadin-upload/pull/378. We will include the fix to the next patch release.

**Comment by sissbruecker** [comment]
Yeah nevermind, thanks to @sosa-vaadin for backporting it.

**Comment by lmorocz** [comment]
Confirmed: fixed in [Vaadin 14.6.8](https://github.com/vaadin/platform/releases/tag/14.6.8), thanks again!
