### ISSUE TITLE
Data binding files for other element attribute

### ISSUE THREAD

**Issue by samiheikki** [vaadin/vaadin-upload#39]
[https://jsbin.com/pukibiviqa/edit?html,js,output](https://jsbin.com/pukibiviqa/edit?html,js,output)

vaadin-upload's `files` property initial value does not work with data binding.
In the example when I add one file and then remove it, data binding works as expected.

**Comment by platosha** [comment]
The cause is the same as in #40, I assume.

The fix is also the same: the `files` array needs to be initialised in the scope of application.

**Comment by samiheikki** [comment]
But using it same way in date-picker works.
[https://jsbin.com/tuvogavuyu/2/edit?html,js,output](https://jsbin.com/tuvogavuyu/2/edit?html,js,output)
