### ISSUE TITLE
Data binding files to dom-repeat

### ISSUE THREAD

**Issue by samiheikki** [vaadin/vaadin-upload#40]
[https://jsbin.com/dunusixuti/edit?html,js,output](https://jsbin.com/dunusixuti/edit?html,js,output)

Data binding `files` for `dom-repeat` does not work.
`Uncaught TypeError: Cannot read property 'concat' of undefined`

**Comment by tehapo** [comment]
I think this is actually not an issue. Looking at the JS Bin link, it seems that you have not defined any initial value for the bound `files` property -> `undefined` value.

Adding an `id="app"` to the dom-bind template and the following line to the end of the JavaScript, you see that it starts to work just fine.
`document.querySelector('#app').files = [];`

**Comment by platosha** [comment]
Good point. Agree with @tehapo.

**Comment by tehapo** [comment]
Now that I took another look, I noticed that the `files` property of `vaadin-upload` is missing the `notify: true` that is required for two-way data-binding. Adding that would also fix the case of this JSBin example.

But there is also a `TODO` comment for the `files` property which hints that is should be made private.

**Comment by manolo** [comment]
Yes, the notify flag was the problem.

Related with making this private, I think it's better to leave it public so as users can bind to it, and customize their UI showing the file content, or whatever they want, and it should be documented.

We can discuss about files being or not public in this issue / PR though
