### ISSUE TITLE
DX user testing findings

### ISSUE THREAD

**Issue by samiheikki** [vaadin/vaadin-upload#43]
- MaxFileSize property
  - maxFileSize needs a better description (what unit to use)
  - Could it be possible to use other values than bytes? (15, 1000, 10MB, 12GB…)
- Features used in demo should be in the API also.
  - --primary-color, --dark-primary-color etc.
  - Setting Custom Drop Label

**Comment by jounik** [comment]
All the issues should be handled already, or split into individual issues.
