### ISSUE TITLE
Safari 8: Status remains in 'Upload cancelled'

### ISSUE THREAD

**Issue by manolo** [vaadin/vaadin-upload#57]
After cancelling the file, the file stays in the list with “Upload cancelled” status.

Bug found during the [UX testing](https://docs.google.com/document/d/12B7KE2PbWBKHO0JakMRcePo6bfD3jn5oiz0XrVl7FgI)

**Comment by tehapo** [comment]
Seems that this issue cannot be reproduced anymore.

Tested with the same Safari 8 test laptop and the same test application that was used in the UX testing. Some other change has most likely fixed this as a side effect.
