### ISSUE TITLE
Error notifications are difficult to realise

### ISSUE THREAD

**Issue by manolo** [vaadin/vaadin-upload#59]
paper-toast is not enough for displaying errors. The notification is easy to miss and disappears to quickly.

Suggestion done during the [UX testing](https://docs.google.com/document/d/12B7KE2PbWBKHO0JakMRcePo6bfD3jn5oiz0XrVl7FgI)

**Comment by platosha** [comment]
Note that there's no paper-toast in the upload. Currently it's up to developer how to display error messages.

In the scope of the upload we need to suggest a good way for that with an example in documentation, I think.

**Comment by jounik** [comment]
@tuomasnironen could make a suggestion of a good way to show various error notifications regarding uploading. After that we could write code examples of those in the documentation.

**Comment by tomivirkki** [comment]
Closing as inactive
