### ISSUE TITLE
Detect offline/online

### ISSUE THREAD

**Issue by manolo** [vaadin/vaadin-upload#64]
It might make sense to detect offline/online mode. Some indication of offline mode might be helpful. May be restart the uploading automatically when back online after connection failure.

Suggestion done during the [UX testing](https://docs.google.com/document/d/12B7KE2PbWBKHO0JakMRcePo6bfD3jn5oiz0XrVl7FgI)

**Comment by manolo** [comment]
Because of the complexity of detecting online/offline in different devices and platforms -for instance [phonegap in android](https://dev.vaadin.com/ticket/13250) - I think this should be something controlled by the app, as a whole. The component could have some methods to indicate go off-line/on-line

**Comment by tomivirkki** [comment]
Haven't heard further requests for this feature and as mentioned, an application can have its own means to indicate offline. Other components, like grid/combo-box using a dataProvider, also require online state but there are no plans to design offline indicators for them either. Closing as inactive.
