### ISSUE TITLE
Active color when 'Processing file' not noticeable

### ISSUE THREAD

**Issue by manolo** [vaadin/vaadin-upload#76]
When using default colors (/demo-pages-shared-styles.html not imported), the `--paper-progress-active-color` for the indeterminate status and progress == 100% is not distinguishable  

  <link rel="import" href="../../iron-demo-helpers/demo-pages-shared-styles.html">

**Comment by web-padawan** [comment]
Closing as outdated. The `paper-progress` dependency has been dropped before V10 version.
