### ISSUE TITLE
Add an option to upload as base64

### ISSUE THREAD

**Issue by fleckdalm** [vaadin/vaadin-upload#90]
It would be great to have an option to get the file contents as base64 for later usage in the code.

**Comment by jounik** [comment]
Can you describe a use case in more detail, what way you would use this feature? It’s not immediately obvious to me at least.

**Comment by fleckdalm** [comment]
I'm sorry I think I may have paraphrased it in an ambigious way.
What I intent to do is to read the file in Javascript to a base64 String (I'm currently doing it using FileReader.readAsDataURL() but would like to use your nice looking widget) without actually uploading it to a server. The use case is that it can be displayed to the user before actually uploading it to the server or doing something else with it. This can be done by showing it (in my code) in an img Tag like src="data:image/png;base64,[base64Code]" or in an audio element...

**Comment by platosha** [comment]
Hi! There's a way to use FileReader.readAsDataURL() together with the upload to do this. Just listen for the “upload-before” event. In the listener you can read the file contents and prevent the uploading request, if needed. Please try:
```javascript
var upload = document.querySelector('vaadin-upload');
upload.addEventListener('upload-before', function(event) {
  event.preventDefault(); // prevents the uploading request
  var fileDataURL = FileReader.readAsDataURL(event.detail.file);
  // ...
});
```

**Comment by fleckdalm** [comment]
Thanks, this basically works!
Is it possible to manually set the state of the progress bar and the upload finished state when using it like this?

**Comment by jounik** [comment]
@fleckdalm something like 
```javascript
upload.files[0].progress = 100;
upload.files[0].complete = true;
``` 
could do the trick.

**Comment by platosha** [comment]
It is possible, but requires some work.

Each file object has a few additional properties reflecting its upload state. They're listed in the [API doc](https://cdn.vaadin.com/vaadin-core-elements/master/vaadin-upload/#vaadin-upload:property-files).

You can change these properties manually, but you'll have to take care about notifying the `files` array property of the upload about these changes to update the upload element. E.g.: call `upload.set(['files', upload.files.indexOf(file), 'progress'], newValue);` to set the value of 'progress' property, and so on.

**Comment by fleckdalm** [comment]
Thank you! :)

**Comment by platosha** [comment]
Looks like the issue subject is resolved already. Closing.

Feel free to make another issue, if needed.

**Comment by LeongTitanFour** [comment]
How can it store the array of images base64 in the local storage within vaadin-upload?
