### ISSUE TITLE
Option to upload binary stream directly without form data?

### ISSUE THREAD

**Issue by Bulan** [vaadin/vaadin-upload#96]
I have a backend service that want's a blob (https://developer.mozilla.org/en-US/docs/Web/API/Blob) sent directly without some form wrapper.
I'm using blob-util (http://nolanlawson.github.io/blob-util/ )  in a related project with something like this:

`$http.post(url,contentBlob,{})`

Is this possible in some way?

Maybe related to this: https://github.com/vaadin/vaadin-upload/issues/90 ?

**Comment by Bulan** [comment]
I made it work the way I wanted by doing this:

Added a new property `mode`, which is used to set the upload mode.

Then I did this in `_uploadFile` function:

`      if (this.mode.toUpperCase() === 'RAW') {
        xhr.send(file);
      } else {
        xhr.send(formData);
      }
`

**Is this something you could add to your component? **
Should I create a pull request to get it in there?

**Comment by Saulis** [comment]
Hi!

Thanks for the report, if you can, a PR would be great!
